// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/home": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/chat" | "/home";
  };
  "./auth/authPages.tsx": {
    id: "auth/authPages";
    page: "/";
  };
  "./chat/messages.tsx": {
    id: "chat/messages";
    page: "/chat";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/home";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "auth/authPages": typeof import("./app/./auth/authPages.tsx");
  "chat/messages": typeof import("./app/./chat/messages.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
};